name: Update jogos.json daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"   # todo dia 09:00 UTC (qualquer horário; isso dá 06:00 no Brasil UTC-3)

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Update jogos.json
        run: python scripts/update_jogos.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add jogos.json
          git commit -m "update jogos.json" || exit 0
          git push
